sonar.projectKey=fuzzy-neuro-optimizer
sonar.projectName=FuzzyNeuroOptimizer
sonar.projectVersion=1.0

sonar.sources=client,server,shared

sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**